# Generated by Django 4.2.9 on 2026-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='Comma separated skills', max_length=255, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
