# Generated by Django 4.2.9 on 2026-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('icon_class', models.CharField(blank=True, default='fa-solid fa-trophy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('date_range', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('titles', models.CharField(help_text='Comma or dot separated titles', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Full Stack Developer | AI Enthusiast', max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField(blank=True, default='https://github.com/adityamalviya')),
                ('summary', models.TextField()),
                ('career_vision', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Top Skills', 'Top Skills'), ('Languages', 'Languages')], max_length=100)),
                ('proficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('proficiency_percent', models.IntegerField(default=70, help_text='0-100 for progress bars')),
                ('icon_class', models.CharField(blank=True, default='', help_text='Font Awesome class e.g. fa-brands fa-python', max_length=100)),
            ],
        ),
    ]
